### ISSUE TITLE
Whats the point of this software?

### ISSUE THREAD

**Issue by masterofobzene** [multimediamike/MobyCAIRO#3]
I mean, if it cannot rotate and crop in batches, its absolutely redundant vs the stock windows photos app.

**Comment by multimediamike** [comment]
Thanks for the feedback. I'm always looking for ways to accelerate workflows with this tool.

Do you have suggestions for how the batch processing would work? Should the GUI allow for selecting a directory of images for processing? Or just multiple selections within a file dialog box? Or are you referring the ability to apply the same rotation and crop operations to a batch of images?

Also, does the default Windows photo app have algorithms for automatically straightening images and detecting circles for cropping? If it does, I'm going to feel a bit silly because I wrote this software specifically because I could not find tools to address this specific workflow.

**Comment by masterofobzene** [comment]
Well... when someone reads:
"MobyCAIRO stands for Computer-Assisted Image ROtation. It is designed to assist a user in the common, **tedious tasks of rotating and cropping images**." 

Doesn't think of a software that levels and straightens but a software that can batch rotate and/or crop MANY images in one go. 

Windows stock photos app lets you rotate as any other apps but in the 4 ways possible with no fine corrections. 
You may advertise this app as an image straightening, cropping or rotating tool but don't say anything about "tedious tasks" because you still need to go one by one.
Also most people will rotate in the 4 possible directions and no corrections are needed, but that doesn't mean this app should not exist, it only needs a better description IMO.

Some apps are starting to use AI to do this (content aware), you may want to search for them.

**Comment by multimediamike** [comment]
Closing in favor of this issue:

https://github.com/multimediamike/MobyCAIRO/issues/4
